export const routes = {
  root: "/",
  onboardingWelcome: "/onboarding/welcome",
  onboardingValues: "/onboarding/values",
  onboardingVision: "/onboarding/vision",
  onboardingReality: "/onboarding/reality",
  onboardingObstacles: "/onboarding/obstacles",
  onboardingSeason: "/onboarding/season",
  onboardingGoals: "/onboarding/goals",
  onboardingNarrow: "/onboarding/narrow",
  onboardingKeystone: "/onboarding/keystone",
  onboardingWeekSetup: "/onboarding/week-setup",
  onboardingPreview: "/onboarding/preview",
  onboardingHabits: "/onboarding/habits",
  onboardingRemove: "/onboarding/remove",
  onboardingGreyMode: "/onboarding/grey-mode",
  onboardingObstacleMitigation: "/onboarding/obstacle-mitigation",
  today: "/today",
  week: "/week",
  timeline: "/timeline",
  journal: "/journal",
  focus: "/focus",
  learn: "/learn",
  relapse: "/relapse",
  seasonEnd: "/season-end",
  seasons: "/seasons",
  seasonDetail: "/seasons/:seasonId",
  settings: "/settings",
  library: "/library",
  notebook: "/notebook",
  packs: "/packs",
  login: "/login",
  signup: "/signup"
} as const;

export const onboardingOrder = [
  routes.onboardingWelcome,
  routes.onboardingValues,
  routes.onboardingReality,
  routes.onboardingObstacles,
  routes.onboardingHabits,
  routes.onboardingRemove,
  routes.onboardingGreyMode,
  routes.onboardingGoals,
  routes.onboardingSeason,
  routes.onboardingVision,
  routes.onboardingNarrow,
  routes.onboardingKeystone,
  routes.onboardingObstacleMitigation,
  routes.onboardingWeekSetup,
  routes.onboardingPreview
] as const;
